FROM python:3.10-slim

WORKDIR /opt/fl

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt \
    --extra-index-url https://download.pytorch.org/whl/cpu

COPY . .

CMD ["python", "client.py"]
